name: ci

on:
  push:
  pull_request:
    branches: [ main ]
    paths:
    - 'src/dotnet/GitHubCrawler/**'

end:
  DOTNET_VERSION: '6.0.401'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}
      - name: Install dependencies
        run: dotnet restore
        working-directory: ./src/dotnet/GitHubCrawler
